# General Shell Commands
alias ls='ls -GFh'
alias cls='clear;ls -a'
alias t='time'
alias c='clear'
alias s='source'
alias v='vim'

# Git Commands
alias gcd='git checkout develop'
alias gs='git status'
alias gss='git status -s'
alias gl='git log --date-order --graph --decorate=full'
alias gl5='git log -5 --date-order --graph --decorate=full'
alias gb='git branch'
alias gco='git checkout'
alias gp='git push'
alias ga='git add'
alias gf='git fetch'
alias gd='git diff'
alias gpro='git pull --rebase=preserve origin'
